import type { PropertyWithImages } from '@/types/supabase'
import type { Agent, Profile } from '@/types/supabase'

export type AgentWithDetails = Agent & {
  profiles: Profile
  properties: { id: string }[]
}

/**
 * Demo/mock property data used for preview when Supabase is not connected.
 * Images are served from Unsplash (may be blocked in restricted environments).
 */
export const DEMO_PROPERTIES: PropertyWithImages[] = [
  {
    id: 'demo-1',
    agent_id: 'agent-1',
    title: 'Rumah Modern Minimalis Kawasan Elit Kebayoran Baru',
    description: 'Rumah modern dengan desain minimalis di kawasan elit Kebayoran Baru. Dikelilingi fasilitas lengkap, akses mudah ke pusat bisnis Jakarta.',
    type: 'rumah',
    status: 'jual',
    price: 4_500_000_000,
    land_area: 250,
    building_area: 350,
    bedrooms: 4,
    bathrooms: 3,
    city: 'Jakarta Selatan',
    district: 'Kebayoran Baru',
    address: 'Jl. Senopati No. 12',
    latitude: -6.2382,
    longitude: 106.8059,
    amenities: ['kolam renang', 'carport', 'taman', 'keamanan 24 jam'],
    is_published: true,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    property_images: [
      {
        id: 'img-1-1',
        property_id: 'demo-1',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-1',
      user_id: 'user-1',
      bio: 'Agen properti berpengalaman 10 tahun di Jakarta.',
      coverage_areas: ['Jakarta Selatan', 'Jakarta Pusat'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-01-01T00:00:00Z',
      slug: 'budi-santoso',
      created_at: '2025-01-01T00:00:00Z',
      profiles: {
        id: 'user-1',
        full_name: 'Budi Santoso',
        avatar_url: null,
        phone: '+62812345678',
        role: 'agent',
        created_at: '2025-01-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-2',
    agent_id: 'agent-2',
    title: 'Apartemen Premium View Kota Sudirman Central Business',
    description: 'Apartemen premium dengan pemandangan kota Jakarta yang spektakuler. Fasilitas bintang lima, lokasi strategis di jantung CBD.',
    type: 'apartemen',
    status: 'jual',
    price: 2_800_000_000,
    land_area: null,
    building_area: 95,
    bedrooms: 2,
    bathrooms: 2,
    city: 'Jakarta Pusat',
    district: 'Sudirman',
    address: 'SCBD, Jl. Jendral Sudirman',
    latitude: -6.2241,
    longitude: 106.8080,
    amenities: ['kolam renang', 'gym', 'concierge', 'parking'],
    is_published: true,
    created_at: '2026-03-05T00:00:00Z',
    updated_at: '2026-03-05T00:00:00Z',
    property_images: [
      {
        id: 'img-2-1',
        property_id: 'demo-2',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-2',
      user_id: 'user-2',
      bio: 'Spesialis properti premium dan komersial Jakarta.',
      coverage_areas: ['Jakarta Pusat', 'Jakarta Selatan'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-02-01T00:00:00Z',
      slug: 'siti-rahayu',
      created_at: '2025-02-01T00:00:00Z',
      profiles: {
        id: 'user-2',
        full_name: 'Siti Rahayu',
        avatar_url: null,
        phone: '+62819876543',
        role: 'agent',
        created_at: '2025-02-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-3',
    agent_id: 'agent-3',
    title: 'Villa Mewah Tepi Pantai Seminyak Bali dengan Kolam Renang Infinity',
    description: 'Villa eksotis dengan kolam renang infinity menghadap Samudra Hindia. Desain arsitektur Bali modern, cocok untuk investasi villa rental.',
    type: 'villa',
    status: 'jual',
    price: 12_000_000_000,
    land_area: 600,
    building_area: 450,
    bedrooms: 5,
    bathrooms: 5,
    city: 'Badung',
    district: 'Seminyak',
    address: 'Jl. Kayu Aya, Seminyak',
    latitude: -8.6917,
    longitude: 115.1617,
    amenities: ['kolam renang infinity', 'outdoor kitchen', 'taman tropis', 'akses pantai privat'],
    is_published: true,
    created_at: '2026-03-08T00:00:00Z',
    updated_at: '2026-03-08T00:00:00Z',
    property_images: [
      {
        id: 'img-3-1',
        property_id: 'demo-3',
        url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-3',
      user_id: 'user-3',
      bio: 'Spesialis properti luxury Bali dengan pengalaman 15 tahun.',
      coverage_areas: ['Bali', 'Lombok'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-03-01T00:00:00Z',
      slug: 'made-wijaya',
      created_at: '2025-03-01T00:00:00Z',
      profiles: {
        id: 'user-3',
        full_name: 'Made Wijaya',
        avatar_url: null,
        phone: '+62822345678',
        role: 'agent',
        created_at: '2025-03-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-4',
    agent_id: 'agent-1',
    title: 'Ruko Strategis 3 Lantai di Pusat Perbelanjaan Surabaya Barat',
    description: 'Ruko komersial 3 lantai dengan lokasi sangat strategis di koridor bisnis utama Surabaya Barat. Cocok untuk berbagai usaha retail dan kantor.',
    type: 'ruko',
    status: 'jual',
    price: 3_200_000_000,
    land_area: 120,
    building_area: 360,
    bedrooms: null,
    bathrooms: 4,
    city: 'Surabaya',
    district: 'Surabaya Barat',
    address: 'Jl. Raya Darmo Permai III',
    latitude: -7.2931,
    longitude: 112.7073,
    amenities: ['parkir luas', 'genset', 'AC central', 'lift'],
    is_published: true,
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
    property_images: [
      {
        id: 'img-4-1',
        property_id: 'demo-4',
        url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-1',
      user_id: 'user-1',
      bio: 'Agen properti berpengalaman 10 tahun di Jakarta.',
      coverage_areas: ['Jakarta Selatan', 'Jakarta Pusat'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-01-01T00:00:00Z',
      slug: 'budi-santoso',
      created_at: '2025-01-01T00:00:00Z',
      profiles: {
        id: 'user-1',
        full_name: 'Budi Santoso',
        avatar_url: null,
        phone: '+62812345678',
        role: 'agent',
        created_at: '2025-01-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-5',
    agent_id: 'agent-2',
    title: 'Tanah Kavling Premium Pegunungan Bandung Timur 2000m²',
    description: 'Tanah kavling premium di kawasan perumahan mewah Bandung Timur. View pegunungan, udara sejuk, siap bangun.',
    type: 'tanah',
    status: 'jual',
    price: 1_800_000_000,
    land_area: 2000,
    building_area: null,
    bedrooms: null,
    bathrooms: null,
    city: 'Bandung',
    district: 'Bandung Timur',
    address: 'Kawasan Perumahan Arcamanik',
    latitude: -6.9344,
    longitude: 107.6791,
    amenities: ['akses jalan aspal', 'listrik tersedia', 'air PDAM', 'SHM'],
    is_published: true,
    created_at: '2026-03-12T00:00:00Z',
    updated_at: '2026-03-12T00:00:00Z',
    property_images: [
      {
        id: 'img-5-1',
        property_id: 'demo-5',
        url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-2',
      user_id: 'user-2',
      bio: 'Spesialis properti premium dan komersial Jakarta.',
      coverage_areas: ['Jakarta Pusat', 'Jakarta Selatan'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-02-01T00:00:00Z',
      slug: 'siti-rahayu',
      created_at: '2025-02-01T00:00:00Z',
      profiles: {
        id: 'user-2',
        full_name: 'Siti Rahayu',
        avatar_url: null,
        phone: '+62819876543',
        role: 'agent',
        created_at: '2025-02-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-6',
    agent_id: 'agent-3',
    title: 'Apartemen Sewa Bulanan Fully Furnished Menteng Jakarta Pusat',
    description: 'Apartemen fully furnished siap huni di Menteng Jakarta Pusat. Dekat dengan pusat hiburan, restoran, dan area bisnis.',
    type: 'apartemen',
    status: 'sewa',
    price: 18_000_000,
    land_area: null,
    building_area: 65,
    bedrooms: 1,
    bathrooms: 1,
    city: 'Jakarta Pusat',
    district: 'Menteng',
    address: 'Jl. Imam Bonjol, Menteng',
    latitude: -6.2008,
    longitude: 106.8325,
    amenities: ['fully furnished', 'AC', 'wifi', 'parking', 'gym'],
    is_published: true,
    created_at: '2026-03-15T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
    property_images: [
      {
        id: 'img-6-1',
        property_id: 'demo-6',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-3',
      user_id: 'user-3',
      bio: 'Spesialis properti luxury Bali dengan pengalaman 15 tahun.',
      coverage_areas: ['Bali', 'Lombok'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-03-01T00:00:00Z',
      slug: 'made-wijaya',
      created_at: '2025-03-01T00:00:00Z',
      profiles: {
        id: 'user-3',
        full_name: 'Made Wijaya',
        avatar_url: null,
        phone: '+62822345678',
        role: 'agent',
        created_at: '2025-03-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-7',
    agent_id: 'agent-1',
    title: 'Rumah Townhouse Cluster Premium Pondok Indah 3+1 Kamar',
    description: 'Townhouse premium dalam cluster eksklusif di Pondok Indah. Desain kontemporer, keamanan 24 jam, fasilitas kolam renang komunal.',
    type: 'rumah',
    status: 'jual',
    price: 6_750_000_000,
    land_area: 200,
    building_area: 280,
    bedrooms: 4,
    bathrooms: 3,
    city: 'Jakarta Selatan',
    district: 'Pondok Indah',
    address: 'Jl. Metro Pondok Indah',
    latitude: -6.2681,
    longitude: 106.7890,
    amenities: ['kolam renang komunal', 'keamanan 24 jam', 'CCTV', 'taman bermain'],
    is_published: true,
    created_at: '2026-03-18T00:00:00Z',
    updated_at: '2026-03-18T00:00:00Z',
    property_images: [
      {
        id: 'img-7-1',
        property_id: 'demo-7',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-1',
      user_id: 'user-1',
      bio: 'Agen properti berpengalaman 10 tahun di Jakarta.',
      coverage_areas: ['Jakarta Selatan', 'Jakarta Pusat'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-01-01T00:00:00Z',
      slug: 'budi-santoso',
      created_at: '2025-01-01T00:00:00Z',
      profiles: {
        id: 'user-1',
        full_name: 'Budi Santoso',
        avatar_url: null,
        phone: '+62812345678',
        role: 'agent',
        created_at: '2025-01-01T00:00:00Z',
      },
    },
  },
  {
    id: 'demo-8',
    agent_id: 'agent-2',
    title: 'Gudang Industri Modern Cikarang Bekasi 5000m² Sertifikat HGB',
    description: 'Gudang industri modern di kawasan industri Cikarang. Tinggi plafon 12 meter, loading dock 4 pintu, akses tol langsung.',
    type: 'gudang',
    status: 'sewa',
    price: 120_000_000,
    land_area: 5000,
    building_area: 4500,
    bedrooms: null,
    bathrooms: 4,
    city: 'Bekasi',
    district: 'Cikarang',
    address: 'Kawasan Industri EJIP, Cikarang',
    latitude: -6.3472,
    longitude: 107.1467,
    amenities: ['loading dock', 'akses tol', 'listrik 3 phase', 'fire suppression'],
    is_published: true,
    created_at: '2026-03-20T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
    property_images: [
      {
        id: 'img-8-1',
        property_id: 'demo-8',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
        is_primary: true,
        sort_order: 0,
      },
    ],
    agents: {
      id: 'agent-2',
      user_id: 'user-2',
      bio: 'Spesialis properti premium dan komersial Jakarta.',
      coverage_areas: ['Jakarta Pusat', 'Jakarta Selatan'],
      ktp_url: null,
      license_url: null,
      is_verified: true,
      verified_at: '2025-02-01T00:00:00Z',
      slug: 'siti-rahayu',
      created_at: '2025-02-01T00:00:00Z',
      profiles: {
        id: 'user-2',
        full_name: 'Siti Rahayu',
        avatar_url: null,
        phone: '+62819876543',
        role: 'agent',
        created_at: '2025-02-01T00:00:00Z',
      },
    },
  },
]


export const DEMO_AGENTS: AgentWithDetails[] = [
  {
    id: 'agent-1',
    user_id: 'user-1',
    bio: 'Agen properti berpengalaman 10 tahun di Jakarta. Spesialis rumah mewah di kawasan premium Jakarta Selatan dan Pusat.',
    coverage_areas: ['Jakarta Selatan', 'Jakarta Pusat', 'Jakarta Barat'],
    ktp_url: null,
    license_url: null,
    is_verified: true,
    verified_at: '2025-01-01T00:00:00Z',
    slug: 'budi-santoso',
    created_at: '2025-01-01T00:00:00Z',
    profiles: {
      id: 'user-1',
      full_name: 'Budi Santoso',
      avatar_url: null,
      phone: '+62812345678',
      role: 'agent',
      created_at: '2025-01-01T00:00:00Z',
    },
    properties: [{ id: 'demo-1' }, { id: 'demo-4' }, { id: 'demo-7' }],
  },
  {
    id: 'agent-2',
    user_id: 'user-2',
    bio: 'Spesialis properti premium dan komersial. Berpengalaman dalam transaksi apartemen, ruko, dan gedung komersial.',
    coverage_areas: ['Jakarta Pusat', 'Jakarta Selatan', 'Bandung', 'Bekasi'],
    ktp_url: null,
    license_url: null,
    is_verified: true,
    verified_at: '2025-02-01T00:00:00Z',
    slug: 'siti-rahayu',
    created_at: '2025-02-01T00:00:00Z',
    profiles: {
      id: 'user-2',
      full_name: 'Siti Rahayu',
      avatar_url: null,
      phone: '+62819876543',
      role: 'agent',
      created_at: '2025-02-01T00:00:00Z',
    },
    properties: [{ id: 'demo-2' }, { id: 'demo-5' }, { id: 'demo-8' }],
  },
  {
    id: 'agent-3',
    user_id: 'user-3',
    bio: 'Spesialis properti luxury Bali dengan pengalaman 15 tahun. Menangani villa, resort, dan properti beachfront premium.',
    coverage_areas: ['Bali', 'Lombok', 'Nusa Tenggara'],
    ktp_url: null,
    license_url: null,
    is_verified: true,
    verified_at: '2025-03-01T00:00:00Z',
    slug: 'made-wijaya',
    created_at: '2025-03-01T00:00:00Z',
    profiles: {
      id: 'user-3',
      full_name: 'Made Wijaya',
      avatar_url: null,
      phone: '+62822345678',
      role: 'agent',
      created_at: '2025-03-01T00:00:00Z',
    },
    properties: [{ id: 'demo-3' }, { id: 'demo-6' }],
  },
]
